### ISSUE TITLE
CRUD Users

### ISSUE THREAD

**Issue by camiloh95** [camiloh95/vote#4]
Create the model and the controller, could be important to take into account the view of the frontend side

**Comment by pipelinevp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
forgng, @GQhighroller, @hieupgmr202, @rustanacexd, @mattzcarey, @pmconnolly80, @tayharris, @firebuggirl, @navarretega, @metaver5o, @HillLiu, @Myzh, @Zerofisher, @wailinkyaww, @anton-karlovskiy, @esthervillars, @shaoye, @marianboda, @hpduong, @paraskumarop, @ipudu, @robertoriy, @flyingnaga2020, @awsaavedra, @RobinJesba, @Salahedeen, @NexZhu, @waealobidallah, @gre4ixin, @ecklf, @Hokore-Dev, @DeanRossouw, @stanley0010, @blakelapierre, @StreetMogu1, @xup3rr, @hardb, @filedos, @dengbuqi, @AkashV420, @guilngou, @daisuke310vvv, @gaemi, @p-janik, @rekingbc, @mutalisk999, @dostu, @tlylt, @lleonesouza, @burakozkirdenizchaintesting, @pfeifferj, @bulbasaursg, @kavu, @robcodehub, @masato25, @agdolla, @sora54, @jzarca01, @g1stavo, @ramy-gendy, @johnsonbhaskaran, @gustavomts, @scalybur, @thekilladro, @YuriSukhorukov, @maogongyin, @EM28715, @setkyar, @behkod, @FAVE01, @mascott82, @kekeho, @msdongx, @zhangfan6644777, @maniac1122, @gocanto, @rl7x, @zdrift3r, @realytcracker, @janclarin, @tonyjunkes, @Hyperzsb, @jlosito, @EribertoLopez, @Aman1337g, @moreal, @akhileshthite, @Renomase, @suliman-nm98, @fijimunkii, @7sne, @patinthehat, @loicboset, @majidbop, @njantong, @mikheevshow, @GopherJ, @r1k0, @sanjay270899

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
chapos, @lightrao, @AndresJiAr, @Ajax-dev, @fijimunkii, @marionety, @MountainPops, @Meeken1998, @thekeele, @eigensheep, @0x0042, @thiras, @skill-issue0, @delef, @xiangarciap, @Jurshsmith, @diegolikescode, @rliq, @luke3butler, @paranoidminotaur, @LMesaric, @JohnBox, @joshfisidi, @sadceri, @Ayuyon, @voidint, @heeman84, @Chalo0, @popraf, @caesar1shi, @J-keaper, @0xAliya, @ochudidesterio, @rafaelsachetto, @jasonhuan, @yuzhiyuan, @murka, @chozeur, @cd3vane, @farisT, @Lucid369, @jwma, @gudj0, @vidahaha, @azhu003, @KristofferTolboll2, @shiqimei, @mehdidotcafe, @Thivieira, @Obamma001krgko, @JagodanaDharmendra, @bymattlee, @siraken, @cre-mer, @janusjerom, @oboshto, @Hyperzsb, @metasal1, @Dnayana92, @gustavomts, @oses137, @lijiehelloworld, @plainfatboy, @MountainPops, @lity, @asterisk800, @0xVitalii, @bakarilevy, @sombochea, @simonefrancia, @emrereyiz, @valdeniomarinho, @bdcannon, @akinncar, @yushengguo557, @irazzhivin, @murka, @DrkDevil, @danielgatis, @karnpapon, @azurechen, @777Rob, @mikeoertli, @clementohNZ, @greyireland, @snobvisions, @emanoelmiranda, @teashophouse, @greymithril, @j05u3, @WaterHashira, @nikitavasilev, @phammanhhiep, @popul, @codesve, @Al-Ka-Li, @vipycm, @DavidCai1111, @egulacti
